// Employee Leaves
export const absent_data = {
    holiday : 5,
    sick : 10,
    other : 8,
    available : 14
}

export const employee_absents = [
  {
    key: '1',
    type: 'ลากิจ',
    fromdate: '2020-03-01',
    todate:'2020-03-02',
    fromtime: '00:00',
    totime:'00:00',
    day: '2',
    reason: 'พบแพทย์ รพ.ราชวิถี',
    status: 'New',
    approver: 'Mr.แจ็ค',
    aimage: 'avatar-01.jpg',
    is_full_day: 1,


  },
  {
    key: '2',
    type: 'ลาพักร้อน',
    fromdate: '2020-03-10',
    todate:'2020-03-12',
    fromtime: '00:00',
    totime:'00:00',
    day: '3',
    reason: 'พบแพทย์ รพ.ราชวิถี',
    status: 'New',
    approver: 'Mr.แจ็ค',
    aimage: 'avatar-02.jpg',
    is_full_day: 1,
  },
  {
    key: '3',
    type: 'ลาป่วย',
    fromdate: '2020-03-25',
    todate:'2020-03-25',
    fromtime: '08:30',
    totime:'16:00',
    day: '0',
    reason: 'พบแพทย์ รพ.ราชวิถี',
    status: 'Approved',
    approver: 'Mr.แจ็ค',
    aimage: 'avatar-03.jpg',
    is_full_day: 0,
  },
  {
    key: '4',
    type: 'ลากิจ',
    fromdate: '2020-03-10',
    todate:'2020-03-12',
    fromtime: '00:00',
    totime:'00:00',
    day: '3',
    reason: 'พบแพทย์ รพ.ราชวิถี',
    status: 'Declined',
    approver: 'Mr.แจ็ค',
    aimage: 'avatar-04.jpg',
    is_full_day: 1,
  }
];

// Employee Payslip
export const payslip =
  {
    key : "49029",
    month_year : "กุมภาพันธ์ 2564",
    company_name : "บริษัท เน็ด อินโนเวชั่น จำกัด",
    company_address1 : "3864 ตึกช้าง อาคารบี ชั้น 23 ถ.พหลโยธิน",
    company_address2 : "แขวงจอมพล เขตจตุจักร กทม.10900",
    emp_name : "นาย สำราญ  ยอดธง",
    emp_role : "Web Designer",
    emp_org1 : "ฝ่ายเทคโนโลยีสารสนเทศ",
    emp_org2 : "แผนกพัฒนาซอฟต์แวร์",
    inc_salary : 375000,
    inc_overtime : 2100,
    inc_position : 4500,
    inc_diligence : 1900,
    inc_total : 46000,
    exp_tax : 1200,
    exp_fund : 920,
    exp_leasing_notebook : 2000,
    exp_monthly_loan : 3000,
    exp_total : 7120,
    net_total : 38880,
    net_total_string : "สามหมื่นแปดพันแปดร้อยแปดสิบ",
    slip: "FT-1002"
  };


// Employee Timesheets
export const timesheet_data = [
  {
    key: '1',
    date: '2020-02-01',
    project : '61A กระทรวงการท่องเที่ยวและกีฬา',
    designated_hours: '20',
    actual_hours: '12',
    task: 'หน้าจอ CRUD ขึ้นทะเบียน บ.ทัวร์',
  },
  {
    key: '2',
    date: '2020-02-01',
    project : '61A กระทรวงการท่องเที่ยวและกีฬา',
    designated_hours: '10',
    actual_hours: '12',
    task: 'หน้าจอ CRUD รายการต้นทุน',
  },
  {
    key: '3',
    date: '2020-03-15',
    project : '62B ระบบ POS',
    designated_hours: '8',
    actual_hours: '4',
    task: 'หน้าจอ CRUD ผู้ใช้งาน',
  },
  {
    key: '4',
    date: '2020-03-15',
    project : '62B ระบบ POS',
    designated_hours: '3',
    actual_hours: '5',
    task: 'หน้าจอ Login',
  },
]

export const project_list = [
  {
    label: '61A กระทรวงการท่องเที่ยวและกีฬา',
    value: '61A กระทรวงการท่องเที่ยวและกีฬา',
    hours_total : 100,
    hours_left : 55,
    deadline : '2021-10-30'
  },
  {
    label: '62B ระบบ POS',
    value: '62B ระบบ POS',
    hours_total : 40,
    hours_left : 25,
    deadline : '2021-05-20'
  },
  {
    label: '63C ระบบ HR',
    value: '63C ระบบ HR',
    hours_total : 120,
    hours_left : 120,
    deadline : '2022-01-01'

  }
]

// HR Salary List
export const emp_data = [
  { key: '1', name: 'ไมค์ ไทแลน', id: "FT-1002", email: 'mike@gmail.com',start_date: "2000-01-01",end_date: "", role: "Software Engineer", org:"ฝ่ายเทคโนโลยีสารสนเทศ", salary: "5000", slip: "FT-1002",avatar: 'avatar-01.jpg', action: "ACT"},
  { key: '2', name: 'จอน อัลฟ่า', id: "FT-2000", email: 'john@yahoo.com',start_date: "2021-01-30",end_date: "", role: "Web Designer", org:"ฝ่ายเทคโนโลยีสารสนเทศ", salary: "7000", slip: "FT-2000",avatar: 'avatar-02.jpg', action: "ACT"},
  { key: '3', name: 'ทอม', id: "FT-2005", email: 'john@yahoo.com',start_date: "2020-03-01",end_date:"2021-03-01", role: "Web Designer", org:"ฝ่ายเทคโนโลยีสารสนเทศ", salary: "4000", slip: "FT-2005",avatar: 'avatar-03.jpg', action: "ACT"},
];

export const no_salary_list = [
  {
    label: 'แอนโทธี่ ฮอปส์ : Web developer',
    id: 'FT-1999',
    value: 'FT-1999',
    email : 'anthony@yahoo.com',
    start_date : '2021-10-30',
    role : 'Web Designer',
    salary : 0
  },
  {
    label: 'เจมี่ แลนนิส : Software Engineer',
    id: 'FT-2020',
    value: 'FT-2020',
    email : 'jamie@gmail.com',
    start_date : '2021-10-30',
    role : 'Software Engineer',
    salary : 0
  },
]


// HR Eployee Profile
export const emp_profile =
  {
    id : 'FT-0001',
    avatar: 'avatar-01.jpg',
    name : 'สรงกานต์',
    lastname : 'สำราญราษฎร์',
    name_en : 'Srongkarn',
    lastname_en : 'Samranrad',
    join_date : '2010-01-01',
    role : 'Team Leader',
    org1 : 'ฝ่ายเทคโนโลยีสารสนเทศ',
    org2 : 'แผนกพัฒนาซอฟต์แวร์',
    type : 'Management Team',
    tel : '08652521236',
    email : 'srongkarn.st@gmail.com',
    birth_date: '1985-07-14',
    is_address_same : false,
    address_current : {
      house_number : '171/9999',
      province : 'กรุงเทพมหานคร',
      sub_district : 'สายไหม',
      district : 'คลองถนน',
      tel : '02-5311111'
    },
    address_card : {
      house_number : '',
      province : '',
      sub_district : '',
      district : '',
      tel : ''
    },

    gender : 'ชาย',
    head : 'Jeffery Lalor',
    head_avatar : 'avatar-02.jpg',
    // Personal
    nation : "ต่างชาติ",
    prefix : "นาย",
    thai_id_card : "3-1005-04281-27-9",
    card_expire_date : '2020-06-15',
    passport_id : "123456798ABC",
    passport_expire_date : "2022-06-30",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",

    religion : "พุทธ",
    marital : "สมรส",
    spouse_occupation : "No",
    children : 2,


    account : [
      {
        id : '1',
        bank : 'ทหารไทย',
        account_number : '12345678910',
        account_type : 'ออมทรัพย์',
      },
      {
        id : '2',
        bank : 'กสิกรไทย',
        account_number : '88888888888',
        account_type : 'กระแสรายวัน',
      },
    ],



    contact :
      {
        contact1:
        {
          id : '1',
          name : 'John Doe',
          relation : 'บิดา',
          tel1 : '098-7654321',
          tel2 :  '098-8888888'
        }
      ,
       contact2:
        {
          id : '2',
          name : 'Jane Doe',
          relation : 'มารดา',
          tel1 : '098-999999',
          tel2 : '',
        }
      },

    family :
      [{
          id : '1',
          name : 'John Doe',
          relation : 'บิดา',
          birth_date : '1960-05-20',
          tel : '098-7654321',
        },
        {
          id : '2',
          name : 'Jane Doe',
          relation : 'มารดา',
          birth_date : '1965-01-10',
          tel : '098-7654321',
        },
      ],

    education :
      [{
          id : '1',
          academy : 'International College of Arts and Science (UG)',
          faculty : 'Science',
          subject : 'Computer Science',
          degree : 'Bachelor Degree',
          begin_year : '2000',
          finish_year : '2003',
          grade : '2.84'
        },
        {
          id : '2',
          academy : 'International College of Arts and Science (UG)',
          faculty : 'Science',
          subject : 'Computer Science',
          degree : 'Master Degree',
          begin_year : '2005',
          finish_year : '2008',
          grade : '3.8'
        }
      ],

    experience :
      [{
          id : '1',
          company : 'Zen Corporation',
          role : 'Web designer',
          begin_year : 'Jan 2013',
          finish_year : 'March 2016',
          first_role : 'Graphic designer',
          final_role : 'Web designer',
          start_salary : 25000,
          final_salary : 47000,
          quit_reason : "ย้ายบ้าน",
          period : '3 years 2 month',
        },
        {
          id : '2',
          company : 'Ron-tech',
          role : 'Web designer',
          begin_year : 'Jan 2017',
          finish_year : 'Jan 2019',
          first_role : 'Web designer',
          final_role : 'Web designer',
          start_salary : 40000,
          final_salary : 40000,
          quit_reason : "สนใจงานด้าน 3D Animation",
          period : '2 years',
        },
        {
          id : '3',
          role : '3D Animator',
          company : 'Warner Bros',
          begin_year : 'Feb 2020',
          finish_year : 'Present',
          first_role : '3D Animator',
          final_role : '-',
          start_salary : 35000,
          final_salary : 0,
          quit_reason : "",
          period : '2 years 3 Months',
        },
      ],
  }

export const head_employees = [
  { label: 'John Depp', value: 'John Depp' },
  { label: 'Mike Tyse', value: 'Mike Tyse' },
  { label: 'Jeffery Lalor', value: 'Jeffery Lalor' },
];

// HR Employee List
export const DEFAULT_COMPANY = "บริษัท ทดสอบ จำกัด";
export const all_emp_list = [
  {
    id : 'FT-0001',
    avatar: 'avatar-01.jpg',
    name : 'สรงกานต์',
    lastname : 'สำราญราษฎร์',
    name_en : 'Srongkarn',
    lastname_en : 'Samranrad',
    nickname : 'Karn',
    join_date : '2010-01-01',
    role : 'Team Leader',
    org1 : 'ฝ่ายเทคโนโลยีสารสนเทศ',
    org2 : 'แผนกพัฒนาซอฟต์แวร์',
    type : 'Management Team',
    company : 'Test Company',
    tel : '08652521236',
    nation : "ไทย",
    thai_id_card : "3-1005-04281-27-9",
    passport_id : "123456798ABC",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",
    username : 'srongkarn',
    email : 'srongkarn.st@gmail.com',
    password : 'abc1234',
    permission :
    [
      {
        key: '1',
        module: 'วันหยุด',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '2',
        module: 'การลา',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '3',
        module: 'ลูกค้า',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '4',
        module: 'Projects',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '5',
        module: 'งาน',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '6',
        module: 'Chats',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '7',
        module: 'ทรัพย์สินของบริษัท',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '8',
        module: 'Timing Sheets',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
    ]
  },
  {
    id : 'FT-0002',
    avatar: 'avatar-02.jpg',
    name : 'สองทดสอบ',
    lastname : 'สองสกุล',
    name_en : 'Test',
    lastname_en : 'Test 02',
    nickname : 'Karn',
    join_date : '2010-01-01',
    role : 'Web Designer',
    org1 : 'ฝ่ายเทคโนโลยีสารสนเทศ',
    org2 : 'แผนกพัฒนาซอฟต์แวร์',
    type : 'พนักงาน',
    company : 'Test Company',
    tel : '08652521236',
    nation : "ไทย",
    thai_id_card : "3-1005-04281-27-9",
    passport_id : "123456798ABC",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",
    username : 'srongkarn',
    email : 'srongkarn.st@gmail.com',
    password : 'abc1234',
    permission :
    [
      {
        key: '1',
        module: 'วันหยุด',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '2',
        module: 'การลา',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '3',
        module: 'ลูกค้า',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '4',
        module: 'Projects',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '5',
        module: 'งาน',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '6',
        module: 'Chats',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '7',
        module: 'ทรัพย์สินของบริษัท',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '8',
        module: 'Timing Sheets',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
    ]
  },
  {
    id : 'FT-0003',
    avatar: 'avatar-03.jpg',
    name : 'สามทดสอบ',
    lastname : 'สามสกุล',
    name_en : 'Test',
    lastname_en : 'Test 03',
    nickname : 'Karn',
    join_date : '2010-01-01',
    role : 'Software Engineer',
    org1 : 'ฝ่ายเทคโนโลยีสารสนเทศ',
    org2 : 'แผนกพัฒนาซอฟต์แวร์',
    type : 'Freelance',
    company : 'Test Company',
    tel : '08652521236',
    nation : "ไทย",
    thai_id_card : "3-1005-04281-27-9",
    passport_id : "123456798ABC",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",
    username : 'srongkarn',
    email : 'srongkarn.st@gmail.com',
    password : 'abc1234',
    permission :
    [
      {
        key: '1',
        module: 'วันหยุด',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '2',
        module: 'การลา',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '3',
        module: 'ลูกค้า',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '4',
        module: 'Projects',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '5',
        module: 'งาน',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '6',
        module: 'Chats',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '7',
        module: 'ทรัพย์สินของบริษัท',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '8',
        module: 'Timing Sheets',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
    ]
  },
  {
    id : 'FT-0004',
    avatar: 'avatar-04.jpg',
    name : 'สี่ทดสอบ',
    lastname : 'สี่สกุล',
    name_en : 'Test',
    lastname_en : 'Tester04',
    nickname : 'Karn',
    join_date : '2010-01-01',
    role : 'Team Leader',
    org1 : 'ฝ่ายทดสอบ',
    org2 : 'แผนกพัฒนาซอฟต์แวร์',
    type : 'พนักงาน',
    company : 'Test Company',
    tel : '08652521236',
    nation : "ไทย",
    thai_id_card : "3-1005-04281-27-9",
    passport_id : "123456798ABC",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",
    username : 'srongkarn',
    email : 'srongkarn.st@gmail.com',
    password : 'abc1234',
    permission :
    [
      {
        key: '1',
        module: 'วันหยุด',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '2',
        module: 'การลา',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '3',
        module: 'ลูกค้า',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '4',
        module: 'Projects',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '5',
        module: 'งาน',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '6',
        module: 'Chats',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '7',
        module: 'ทรัพย์สินของบริษัท',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '8',
        module: 'Timing Sheets',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
    ]
  },
  {
    id : 'FT-0005',
    avatar: 'avatar-05.jpg',
    name : 'ห้าทดสอบ',
    lastname : 'ห้าสกุล',
    name_en : 'Test',
    lastname_en : 'Tester 05',
    nickname : 'Karn',
    join_date : '2010-01-01',
    role : 'Web Designer',
    org1 : 'ฝ่ายเทคโนโลยีสารสนเทศ',
    org2 : 'แผนกการตลาด',
    type : 'พนักงาน',
    company : 'Test Company',
    tel : '08652521236',
    nation : "ไทย",
    thai_id_card : "3-1005-04281-27-9",
    passport_id : "123456798ABC",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",
    username : 'srongkarn',
    email : 'srongkarn.st@gmail.com',
    password : 'abc1234',
    permission :
    [
      {
        key: '1',
        module: 'วันหยุด',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '2',
        module: 'การลา',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '3',
        module: 'ลูกค้า',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '4',
        module: 'Projects',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '5',
        module: 'งาน',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '6',
        module: 'Chats',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '7',
        module: 'ทรัพย์สินของบริษัท',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '8',
        module: 'Timing Sheets',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
    ]
  },
  {
    id : 'FT-0006',
    avatar: 'avatar-06.jpg',
    name : 'หกทดสอบ',
    lastname : 'หกสกุล',
    name_en : 'Test',
    lastname_en : '06',
    nickname : 'Karn',
    join_date : '2010-01-01',
    role : 'Web Designer',
    org1 : 'ฝ่ายเทคโนโลยีสารสนเทศ',
    org2 : 'แผนกพัฒนาซอฟต์แวร์',
    type : 'นักศึกษาฝึกงาน',
    company : 'Test Company',
    tel : '08652521236',
    nation : "ไทย",
    thai_id_card : "3-1005-04281-27-9",
    passport_id : "123456798ABC",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",
    username : 'srongkarn',
    email : 'srongkarn.st@gmail.com',
    password : 'abc1234',
    permission :
    [
      {
        key: '1',
        module: 'วันหยุด',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '2',
        module: 'การลา',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '3',
        module: 'ลูกค้า',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '4',
        module: 'Projects',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '5',
        module: 'งาน',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '6',
        module: 'Chats',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '7',
        module: 'ทรัพย์สินของบริษัท',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '8',
        module: 'Timing Sheets',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
    ]
  },
  {
    id : 'FT-0007',
    avatar: 'avatar-07.jpg',
    name : 'เจ็ดทดสอบ',
    lastname : 'เจ็ดสกุล',
    name_en : 'Test',
    lastname_en : 'Test07',
    nickname : 'Karn',
    join_date : '2010-01-01',
    role : 'Software Engineer',
    org1 : 'ฝ่ายเทคโนโลยีสารสนเทศ',
    org2 : 'แผนกการตลาด',
    type : ' พนักงาน',
    company : 'Test Company',
    tel : '08652521236',
    nation : "ไทย",
    thai_id_card : "3-1005-04281-27-9",
    passport_id : "123456798ABC",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",
    username : 'srongkarn',
    email : 'srongkarn.st@gmail.com',
    password : 'abc1234',
    permission :
    [
      {
        key: '1',
        module: 'วันหยุด',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '2',
        module: 'การลา',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '3',
        module: 'ลูกค้า',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '4',
        module: 'Projects',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '5',
        module: 'งาน',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '6',
        module: 'Chats',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '7',
        module: 'ทรัพย์สินของบริษัท',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '8',
        module: 'Timing Sheets',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
    ]
  },
  {
    id : 'FT-0008',
    avatar: 'avatar-08.jpg',
    name : 'แปดทดสอบ',
    lastname : 'แปดสกุล',
    name_en : 'Test ',
    lastname_en : '0808',
    nickname : 'Karn',
    join_date : '2010-01-01',
    role : 'Web Designer',
    org1 : 'ฝ่ายเทคโนโลยีสารสนเทศ',
    org2 : 'แผนกพัฒนาซอฟต์แวร์',
    type : 'พนักงาน',
    company : 'Test Company',
    tel : '08652521236',
    nation : "ไทย",
    thai_id_card : "3-1005-04281-27-9",
    passport_id : "123456798ABC",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",
    username : 'srongkarn',
    email : 'srongkarn.st@gmail.com',
    password : 'abc1234',
    permission :
    [
      {
        key: '1',
        module: 'วันหยุด',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '2',
        module: 'การลา',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '3',
        module: 'ลูกค้า',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '4',
        module: 'Projects',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '5',
        module: 'งาน',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '6',
        module: 'Chats',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '7',
        module: 'ทรัพย์สินของบริษัท',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '8',
        module: 'Timing Sheets',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
    ]
  },
  {
    id : 'FT-0009',
    avatar: 'avatar-09.jpg',
    name : 'เก้าทดสอบ',
    lastname : 'เก้าสกุุล',
    name_en : 'Test',
    lastname_en : 'T09',
    nickname : 'Karn',
    join_date : '2010-01-01',
    role : 'Team Leader',
    org1 : 'ฝ่ายเทคโนโลยีสารสนเทศ',
    org2 : 'แผนกการตลาด',
    type : 'พนักงาน',
    company : 'Test Company',
    tel : '08652521236',
    nation : "ไทย",
    thai_id_card : "3-1005-04281-27-9",
    passport_id : "123456798ABC",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",
    username : 'srongkarn',
    email : 'srongkarn.st@gmail.com',
    password : 'abc1234',
    permission :
    [
      {
        key: '1',
        module: 'วันหยุด',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '2',
        module: 'การลา',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '3',
        module: 'ลูกค้า',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '4',
        module: 'Projects',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '5',
        module: 'งาน',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '6',
        module: 'Chats',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '7',
        module: 'ทรัพย์สินของบริษัท',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '8',
        module: 'Timing Sheets',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
    ]
  },
  {
    id : 'FT-0010',
    avatar: 'avatar-10.jpg',
    name : 'สิบทดสอบ',
    lastname : 'สิบสกุล',
    name_en : 'Test',
    lastname_en : 'T10',
    nickname : 'Karn',
    join_date : '2010-01-01',
    role : 'Team Leader',
    org1 : 'ฝ่ายเทคโนโลยีสารสนเทศ',
    org2 : 'แผนกการตลาด',
    type : 'Management Team',
    company : 'Test Company',
    tel : '08652521236',
    nation : "ไทย",
    thai_id_card : "3-1005-04281-27-9",
    passport_id : "123456798ABC",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",
    username : 'srongkarn',
    email : 'srongkarn.st@gmail.com',
    password : 'abc1234',
    permission :
    [
      {
        key: '1',
        module: 'วันหยุด',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '2',
        module: 'การลา',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '3',
        module: 'ลูกค้า',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '4',
        module: 'Projects',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '5',
        module: 'งาน',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '6',
        module: 'Chats',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '7',
        module: 'ทรัพย์สินของบริษัท',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '8',
        module: 'Timing Sheets',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
    ]
  },
  {
    id : 'FT-00011',
    avatar: 'avatar-01.jpg',
    name : 'สรงกานต์',
    lastname : 'สำราญราษฎร์',
    name_en : 'Srongkarn',
    lastname_en : 'Samranrad',
    nickname : 'Karn',
    join_date : '2010-01-01',
    role : 'Team Leader',
    org1 : 'ฝ่ายเทคโนโลยีสารสนเทศ',
    org2 : 'แผนกพัฒนาซอฟต์แวร์',
    type : 'Management Team',
    company : 'Test Company',
    tel : '08652521236',
    nation : "ไทย",
    thai_id_card : "3-1005-04281-27-9",
    passport_id : "123456798ABC",
    work_permit_id : "P11-999999",
    work_permit_date : "2020-01-15",
    work_permit_expire_date : "2022-09-22",
    username : 'srongkarn',
    email : 'srongkarn.st@gmail.com',
    password : 'abc1234',
    permission :
    [
      {
        key: '1',
        module: 'วันหยุด',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '2',
        module: 'การลา',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '3',
        module: 'ลูกค้า',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '4',
        module: 'Projects',
        read : false,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '5',
        module: 'งาน',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '6',
        module: 'Chats',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '7',
        module: 'ทรัพย์สินของบริษัท',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
      {
        key: '8',
        module: 'Timing Sheets',
        read : true,
        write : true,
        create : true,
        del : false,
        imp : false,
        exp : false,
      },
    ]
  },

]